import { useMemo, useRef, useState } from 'react'; import { Alert, Pressable, StyleSheet, Text, View } from 'react-native'; import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import QRCode from 'react-native-qrcode-svg'; import { captureRef } from 'react-native-view-shot'; import * as Sharing from 'expo-sharing'; import * as MediaLibrary from 'expo-media-library/legacy'; import * as Print from 'expo-print'; import { File } from 'expo-file-system';
import { Screen } from '../components/Screen'; import { Button } from '../components/Button'; import { colors, radius } from '../theme'; import type { RootStackParamList } from '../navigation/types'; import { useApp } from '../hooks/useApp'; import { QRService } from '../services/qr/QRService'; import { canHighResolutionExport } from '../services/revenuecat/proGating'; import { messageFromError } from '../utils/errors';

const cardColors = {classic: {bg: colors.white, fg: colors.ink}, midnight: {bg: colors.midnight, fg: colors.white}, warm: {bg: '#F3E2D2', fg: '#4E2F20'}};
export function CardViewScreen({route, navigation}: NativeStackScreenProps<RootStackParamList, 'CardView'>) {
  const app = useApp(); const card = app.cards.find((item) => item.id === route.params.cardId); const cardRef = useRef<View>(null); const [busy, setBusy] = useState(false);
  const payload = useMemo(() => card && app.identity ? QRService.encodeContactCard(app.identity, card) : '', [card, app.identity]);
  if (!card) return <Screen><Text>Card not found.</Text><Button label="Back to cards" onPress={() => navigation.navigate('Home')}/></Screen>;
  const palette = cardColors[card.style];
  const capture = async (high = false) => captureRef(cardRef, {format: 'png', quality: 1, result: 'tmpfile', width: high ? 2048 : 1024, height: high ? 2688 : 1344});
  const share = async () => { try { setBusy(true); const uri = await capture(false); if (await Sharing.isAvailableAsync()) await Sharing.shareAsync(uri, {mimeType: 'image/png', dialogTitle: `Share ${card.label}`}); } catch (e) { Alert.alert('Could not share', messageFromError(e)); } finally { setBusy(false); } };
  const save = async (high = false) => { if (high && !canHighResolutionExport(app.isPro)) return navigation.navigate('Paywall'); try { setBusy(true); const permission = await MediaLibrary.requestPermissionsAsync(true); if (!permission.granted) throw new Error('Photo permission is needed to save the card image.'); await MediaLibrary.saveToLibraryAsync(await capture(high)); Alert.alert('Saved', high ? 'A high-resolution card was saved.' : 'Your card image was saved.'); } catch (e) { Alert.alert('Could not save', messageFromError(e)); } finally { setBusy(false); } };
  const savePdf = async () => { if (!app.isPro) return navigation.navigate('Paywall'); try { setBusy(true); const png = new File(await capture(true)); const base64 = await png.base64(); const result = await Print.printToFileAsync({html: `<html><body style="margin:0;display:flex;align-items:center;justify-content:center;height:100vh;background:#fff"><img alt="FaceCard QR" style="width:90%;max-width:700px" src="data:image/png;base64,${base64}"/></body></html>`}); if (await Sharing.isAvailableAsync()) await Sharing.shareAsync(result.uri, {mimeType: 'application/pdf'}); } catch (e) { Alert.alert('Could not export PDF', messageFromError(e)); } finally { setBusy(false); } };
  return <Screen><View ref={cardRef} collapsable={false} style={[styles.card, {backgroundColor: palette.bg}]}><Text style={[styles.brand, {color: palette.fg}]}>FACECARD</Text><View style={styles.qrShell}><QRCode value={payload} size={236} color="#000000" backgroundColor="#FFFFFF" ecl="M" quietZone={14}/></View><Text style={[styles.name, {color: palette.fg}]}>{card.displayName}</Text>{card.tagline && <Text style={[styles.tagline, {color: palette.fg}]}>{card.tagline}</Text>}<Text style={[styles.prompt, {color: palette.fg}]}>Scan to receive selected contact details</Text></View>
    <View style={styles.actions}><Button label="Share" loading={busy} onPress={share} style={styles.half}/><Button label="Save image" variant="secondary" disabled={busy} onPress={() => save(false)} style={styles.half}/></View>
    <Button label="Edit shared details" variant="secondary" onPress={() => navigation.navigate('CardEditor', {cardId: card.id})}/><View style={styles.proRow}><Pressable onPress={() => save(true)}><Text style={styles.proAction}>High-resolution export {app.isPro ? '' : '· Pro'}</Text></Pressable><Pressable onPress={savePdf}><Text style={styles.proAction}>Print/PDF {app.isPro ? '' : '· Pro'}</Text></Pressable></View>
    <Button label="Scan another card" variant="text" onPress={() => navigation.navigate('Scanner')}/>
  </Screen>;
}
const styles = StyleSheet.create({card: {borderRadius: radius.lg, paddingHorizontal: 26, paddingVertical: 24, alignItems: 'center', minHeight: 430, justifyContent: 'space-between', shadowColor: '#000', shadowOpacity: .08, shadowRadius: 18, shadowOffset: {width: 0, height: 8}, elevation: 3}, brand: {fontSize: 10, fontWeight: '800', letterSpacing: 2.5, alignSelf: 'flex-start'}, qrShell: {backgroundColor: colors.white, borderRadius: 16, padding: 4}, name: {fontSize: 27, fontWeight: '700', textAlign: 'center'}, tagline: {fontSize: 15, opacity: .72, textAlign: 'center'}, prompt: {fontSize: 11, opacity: .55}, actions: {flexDirection: 'row', gap: 10}, half: {flex: 1}, proRow: {flexDirection: 'row', justifyContent: 'space-around', paddingVertical: 8}, proAction: {fontSize: 13, color: colors.green, fontWeight: '700'}});
