import { Alert, Pressable, StyleSheet, Text, View } from 'react-native'; import { useState } from 'react'; import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Screen } from '../components/Screen'; import { Button } from '../components/Button'; import { FormField } from '../components/FormField'; import { ShareToggle } from '../components/ShareToggle'; import { colors, radius } from '../theme'; import type { RootStackParamList } from '../navigation/types'; import { useApp } from '../hooks/useApp'; import type { CardStyle, ContactCard, ContactFieldKey, ContactFields } from '../models'; import { CONTACT_FIELD_KEYS } from '../models'; import { createLocalId } from '../utils/id'; import { canShareField, canUseStyle } from '../services/revenuecat/proGating'; import { QRService } from '../services/qr/QRService';

const labels: Record<ContactFieldKey, string> = {email: 'Email', phone: 'Phone', website: 'Website', linkedin: 'LinkedIn', github: 'GitHub', company: 'Company', jobTitle: 'Job title', note: 'Optional note'};
const keyboard: Partial<Record<ContactFieldKey, 'email-address' | 'phone-pad' | 'url'>> = {email: 'email-address', phone: 'phone-pad', website: 'url', linkedin: 'url', github: 'url'};
const stylesList: {key: CardStyle; label: string}[] = [{key: 'classic', label: 'Classic'}, {key: 'midnight', label: 'Midnight'}, {key: 'warm', label: 'Warm'}];
export function CardEditorScreen({route, navigation}: NativeStackScreenProps<RootStackParamList, 'CardEditor'>) {
  const app = useApp(); const existing = app.cards.find((card) => card.id === route.params?.cardId);
  const [label, setLabel] = useState(existing?.label ?? (app.cards.length ? 'Personal' : 'My card')); const [displayName, setDisplayName] = useState(existing?.displayName ?? ''); const [tagline, setTagline] = useState(existing?.tagline ?? '');
  const [fields, setFields] = useState<ContactFields>(existing?.fields ?? {}); const [shared, setShared] = useState<ContactFieldKey[]>(existing?.sharedFieldKeys ?? ['email']); const [shareName, setShareName] = useState(existing?.shareDisplayName ?? true); const [style, setStyle] = useState<CardStyle>(existing?.style ?? 'classic');
  const [expiresAt, setExpiresAt] = useState<string | undefined>(existing?.expiresAt);
  const updateField = (key: ContactFieldKey, value: string) => setFields((current) => ({...current, [key]: value}));
  const toggle = (key: ContactFieldKey, enabled: boolean) => setShared((current) => enabled ? [...new Set([...current, key])] : current.filter((item) => item !== key));
  const chooseStyle = (next: CardStyle) => { if (!canUseStyle(next, app.isPro)) return navigation.navigate('Paywall'); setStyle(next); };
  const chooseExpiry = (hours?: number) => { if (hours && !app.isPro) return navigation.navigate('Paywall'); setExpiresAt(hours ? new Date(Date.now() + hours * 3_600_000).toISOString() : undefined); };
  const save = async () => {
    if (!displayName.trim()) return Alert.alert('Add your name', 'A display name is required for the local card, even if you choose not to share it.');
    const card: ContactCard = {id: existing?.id ?? createLocalId('card'), label: label.trim() || 'My card', displayName: displayName.trim(), tagline: tagline.trim() || undefined, fields, shareDisplayName: shareName, sharedFieldKeys: shared.filter((key) => canShareField(key, app.isPro)), style, createdAt: existing?.createdAt ?? new Date().toISOString(), expiresAt};
    try { QRService.encodeContactCard(app.identity!, card); await app.saveCard(card); navigation.replace('CardView', {cardId: card.id}); } catch (error) { Alert.alert('Check card details', error instanceof Error ? error.message : 'Some details are invalid.'); }
  };
  return <Screen><Text style={s.title}>{existing ? 'Edit card' : 'Create your card'}</Text><Text style={s.lead}>Every switch controls what is physically encoded in this QR.</Text>
    <FormField label="Card label" value={label} maxLength={40} onChangeText={setLabel} placeholder="Work, Personal, Conference"/><FormField label="Display name" value={displayName} maxLength={100} onChangeText={setDisplayName}/><ShareToggle label="Share display name" value={shareName} onChange={setShareName}/><FormField label="Tagline (shown only with name)" value={tagline} maxLength={120} onChangeText={setTagline}/>
    <Text style={s.section}>CONTACT FIELDS</Text>{CONTACT_FIELD_KEYS.map((key) => <View key={key} style={s.fieldGroup}><FormField label={labels[key]} value={fields[key] ?? ''} maxLength={key === 'note' ? 280 : 300} keyboardType={keyboard[key] ?? 'default'} autoCapitalize={keyboard[key] ? 'none' : 'sentences'} multiline={key === 'note'} onChangeText={(value) => updateField(key, value)}/><ShareToggle label={`Include ${labels[key].toLowerCase()}`} value={shared.includes(key)} locked={!canShareField(key, app.isPro)} onChange={(value) => toggle(key, value)}/></View>)}
    <Text style={s.section}>CARD STYLE</Text><View style={s.styleRow}>{stylesList.map((item) => <Pressable key={item.key} onPress={() => chooseStyle(item.key)} style={[s.styleChip, style === item.key && s.styleSelected]}><Text style={[s.styleText, style === item.key && s.styleTextSelected]}>{item.label}{item.key !== 'classic' && !app.isPro ? ' · Pro' : ''}</Text></Pressable>)}</View>
    <Text style={s.section}>EXPIRY</Text><View style={s.styleRow}><Pressable onPress={() => chooseExpiry()} style={[s.styleChip, !expiresAt && s.styleSelected]}><Text style={[s.styleText, !expiresAt && s.styleTextSelected]}>Never</Text></Pressable>{[{h: 1, l: '1 hour'}, {h: 24, l: '24 hours'}, {h: 168, l: '7 days'}].map((item) => <Pressable key={item.h} onPress={() => chooseExpiry(item.h)} style={[s.styleChip, expiresAt && Math.abs(Date.parse(expiresAt) - Date.now() - item.h * 3_600_000) < 60_000 && s.styleSelected]}><Text style={s.styleText}>{item.l} · Pro</Text></Pressable>)}</View>
    <Button label="Generate QR card" onPress={save}/>
  </Screen>;
}
const s = StyleSheet.create({title: {fontSize: 34, fontWeight: '700', color: colors.ink, marginTop: 12}, lead: {fontSize: 16, lineHeight: 23, color: colors.muted}, section: {fontSize: 11, letterSpacing: 1.7, color: colors.green, fontWeight: '800', marginTop: 12}, fieldGroup: {backgroundColor: colors.white, borderRadius: radius.md, padding: 12, borderWidth: 1, borderColor: colors.line}, styleRow: {flexDirection: 'row', gap: 8}, styleChip: {paddingHorizontal: 14, paddingVertical: 11, borderWidth: 1, borderColor: colors.line, borderRadius: 99, backgroundColor: colors.white}, styleSelected: {backgroundColor: colors.ink, borderColor: colors.ink}, styleText: {fontSize: 13, color: colors.ink}, styleTextSelected: {color: colors.white, fontWeight: '700'}});
