import { useEffect, useState } from 'react'; import { ActivityIndicator, Alert, StyleSheet, Text, View } from 'react-native';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Screen } from '../components/Screen'; import { colors } from '../theme'; import type { RootStackParamList } from '../navigation/types'; import { identityService, type EnrollmentProgress } from '../services/identity/IdentityService'; import { useApp } from '../hooks/useApp'; import { messageFromError } from '../utils/errors';

const labels: Record<EnrollmentProgress['step'], string> = {detecting: 'Detecting faces', aligning: 'Aligning landmarks', creating: 'Creating visual identity', hashing: 'Generating secure ID', complete: 'Creating QR'};
export function GenerateIdentityScreen({route, navigation}: NativeStackScreenProps<RootStackParamList, 'GenerateIdentity'>) {
  const app = useApp(); const [progress, setProgress] = useState<EnrollmentProgress>({step: 'detecting', current: 0, total: route.params.images.length});
  useEffect(() => { let active = true; (async () => { try { const identity = await identityService.enrollFromImages(route.params.images, (next) => active && setProgress(next)); if (!active) return; await app.setIdentity(identity); navigation.reset({index: 0, routes: [{name: 'CardEditor'}]}); } catch (error) { if (active) Alert.alert('Enrollment needs another try', messageFromError(error), [{text: 'Choose different photos', onPress: () => navigation.goBack()}]); } })(); return () => { active = false; }; }, []);
  const order = Object.keys(labels) as EnrollmentProgress['step'][]; const activeIndex = order.indexOf(progress.step);
  return <Screen contentStyle={styles.screen}><View style={styles.center}><ActivityIndicator size="large" color={colors.ink}/><Text style={styles.title}>Building your private identity</Text><Text style={styles.body}>Everything in this step happens locally on your device.</Text></View>
    <View style={styles.steps}>{order.map((step, index) => <View key={step} style={styles.row}><View style={[styles.dot, index <= activeIndex && styles.dotActive]}/><Text style={[styles.step, index === activeIndex && styles.stepActive]}>{labels[step]}</Text>{step === progress.step && step !== 'complete' && <Text style={styles.count}>{progress.current}/{progress.total}</Text>}</View>)}</View>
  </Screen>;
}
const styles = StyleSheet.create({screen: {flexGrow: 1, justifyContent: 'center'}, center: {alignItems: 'center', gap: 14, marginBottom: 34}, title: {fontSize: 27, fontWeight: '700', color: colors.ink, textAlign: 'center'}, body: {fontSize: 15, color: colors.muted, textAlign: 'center'}, steps: {gap: 18, alignSelf: 'center', width: 280}, row: {flexDirection: 'row', alignItems: 'center', gap: 12}, dot: {width: 10, height: 10, borderRadius: 5, backgroundColor: colors.line}, dotActive: {backgroundColor: colors.green}, step: {flex: 1, color: colors.muted}, stepActive: {fontWeight: '700', color: colors.ink}, count: {fontSize: 12, color: colors.muted}});
