import { Pressable, StyleSheet, Text, View } from 'react-native'; import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Screen } from '../components/Screen'; import { Button } from '../components/Button'; import { colors, radius } from '../theme'; import type { RootStackParamList } from '../navigation/types'; import { useApp } from '../hooks/useApp'; import { canCreateCard } from '../services/revenuecat/proGating';

export function HomeScreen({navigation}: NativeStackScreenProps<RootStackParamList, 'Home'>) {
  const {cards, isPro, identity} = useApp();
  const create = () => canCreateCard(cards.length, isPro) ? navigation.navigate('CardEditor') : navigation.navigate('Paywall');
  return <Screen><View style={styles.header}><View><Text style={styles.eyebrow}>YOUR FACECARDS</Text><Text style={styles.title}>Share with intent.</Text></View><Pressable accessibilityLabel="Settings" onPress={() => navigation.navigate('Settings')} style={styles.settings}><Text style={styles.settingsText}>•••</Text></Pressable></View>
    {cards.length === 0 ? <View style={styles.empty}><Text style={styles.emptyMark}>▦</Text><Text style={styles.emptyTitle}>Your first card is waiting.</Text><Text style={styles.body}>Choose exactly what someone receives when they scan.</Text><Button label="Create contact card" onPress={create}/></View>
      : <View style={styles.list}>{cards.map((card) => <Pressable key={card.id} onPress={() => navigation.navigate('CardView', {cardId: card.id})} style={styles.card}><View><Text style={styles.cardLabel}>{card.label}</Text><Text style={styles.cardName}>{card.displayName}</Text><Text style={styles.shared}>{(card.sharedFieldKeys.length + (card.shareDisplayName ? 1 : 0))} shared fields</Text></View><Text style={styles.arrow}>›</Text></Pressable>)}</View>}
    {cards.length > 0 && <Button label="Create alternate card" variant="secondary" onPress={create}/>}<Button label="Scan a FaceCard" onPress={() => navigation.navigate('Scanner')}/>
    <View style={styles.identity}><Text style={styles.identityLabel}>LOCAL IDENTITY</Text><Text style={styles.identityValue}>{identity?.id.match(/.{1,4}/g)?.slice(0, 4).join(' · ')}</Text><Text style={styles.identityNote}>Derived locally · Never placed in a public registry</Text></View>
  </Screen>;
}
const styles = StyleSheet.create({header: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginTop: 10}, eyebrow: {fontSize: 11, letterSpacing: 1.7, color: colors.green, fontWeight: '800'}, title: {fontSize: 31, fontWeight: '700', color: colors.ink, marginTop: 5}, settings: {width: 44, height: 44, borderRadius: 22, backgroundColor: colors.white, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.line}, settingsText: {fontSize: 17, letterSpacing: 2}, empty: {minHeight: 290, backgroundColor: colors.white, borderRadius: radius.lg, padding: 24, justifyContent: 'center', gap: 12, borderWidth: 1, borderColor: colors.line}, emptyMark: {fontSize: 40}, emptyTitle: {fontSize: 23, fontWeight: '700', color: colors.ink}, body: {fontSize: 15, lineHeight: 22, color: colors.muted}, list: {gap: 10}, card: {backgroundColor: colors.white, padding: 20, borderRadius: radius.md, borderWidth: 1, borderColor: colors.line, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'}, cardLabel: {fontSize: 11, color: colors.green, fontWeight: '800', letterSpacing: 1.3, textTransform: 'uppercase'}, cardName: {fontSize: 21, color: colors.ink, fontWeight: '700', marginTop: 5}, shared: {fontSize: 13, color: colors.muted, marginTop: 4}, arrow: {fontSize: 34, color: colors.muted}, identity: {marginTop: 8, padding: 16, borderTopWidth: 1, borderTopColor: colors.line, gap: 5}, identityLabel: {fontSize: 10, color: colors.muted, letterSpacing: 1.5, fontWeight: '800'}, identityValue: {fontSize: 15, fontVariant: ['tabular-nums'], color: colors.ink}, identityNote: {fontSize: 12, color: colors.muted}});
