import { useEffect, useState } from 'react'; import { Alert, StyleSheet, Text, View } from 'react-native'; import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Screen } from '../components/Screen'; import { Button } from '../components/Button'; import { colors, radius } from '../theme'; import type { RootStackParamList } from '../navigation/types'; import { useApp } from '../hooks/useApp'; import { revenueCatService } from '../services/revenuecat/RevenueCatService'; import { messageFromError } from '../utils/errors';

const benefits = ['Multiple cards for Work, Personal, Conference, and Emergency', 'Midnight and Warm card themes', 'High-resolution QR image export', 'LinkedIn, GitHub, company, title, and notes', 'Non-biometric configuration backup and PDF export'];
export function PaywallScreen({navigation}: NativeStackScreenProps<RootStackParamList, 'Paywall'>) {
  const app = useApp(); const [busy, setBusy] = useState(false); const [price, setPrice] = useState<string | null>(null);
  const purchase = async () => { try { setBusy(true); const result = await app.purchasePro(); if (!result.cancelled && app.isPro) navigation.goBack(); else if (!result.cancelled) navigation.goBack(); } catch (e) { Alert.alert('Purchase unavailable', messageFromError(e)); } finally { setBusy(false); } };
  const restore = async () => { try { setBusy(true); const restored = await app.restorePurchases(); Alert.alert(restored ? 'Pro restored' : 'Nothing to restore', restored ? 'FaceCard Pro is unlocked.' : 'No Pro entitlement was found for this store account.'); if (restored) navigation.goBack(); } catch (e) { Alert.alert('Restore failed', messageFromError(e)); } finally { setBusy(false); } };
  useEffect(() => { if (!revenueCatService.isMockMode()) revenueCatService.getProPackage().then((item) => setPrice(item.product.priceString)).catch(() => undefined); }, []);
  return <Screen><View style={styles.hero}><Text style={styles.badge}>LIFETIME</Text><Text style={styles.title}>FaceCard Pro</Text><Text style={styles.price}>{price ?? (revenueCatService.isMockMode() ? 'Local mock purchase' : 'One-time purchase')}</Text><Text style={styles.lead}>More contexts for your identity. Still no account, feed, tracking, or biometric cloud.</Text></View>
    <View style={styles.benefits}>{benefits.map((benefit) => <View key={benefit} style={styles.row}><Text style={styles.check}>✓</Text><Text style={styles.benefit}>{benefit}</Text></View>)}</View>
    {revenueCatService.isMockMode() && <View style={styles.mock}><Text style={styles.mockText}>Development mock mode is active. Store builds must set EXPO_PUBLIC_REVENUECAT_MOCK=false.</Text></View>}
    <Button label={price ? `Unlock Pro — ${price}` : 'Unlock Pro'} loading={busy} onPress={purchase}/><Button label="Restore purchase" disabled={busy} variant="text" onPress={restore}/><Text style={styles.note}>Non-consumable one-time purchase. Store terms apply.</Text>
  </Screen>;
}
const styles = StyleSheet.create({hero: {alignItems: 'center', gap: 10, paddingTop: 28}, badge: {fontSize: 11, letterSpacing: 1.6, fontWeight: '800', color: colors.green, borderWidth: 1, borderColor: colors.green, borderRadius: 99, paddingHorizontal: 12, paddingVertical: 6}, title: {fontSize: 40, fontWeight: '700', color: colors.ink}, price: {fontSize: 18, fontWeight: '700', color: colors.ink}, lead: {fontSize: 15, lineHeight: 22, color: colors.muted, textAlign: 'center'}, benefits: {backgroundColor: colors.white, borderWidth: 1, borderColor: colors.line, borderRadius: radius.lg, padding: 18}, row: {flexDirection: 'row', gap: 12, paddingVertical: 10}, check: {color: colors.green, fontWeight: '900'}, benefit: {flex: 1, fontSize: 15, lineHeight: 21, color: colors.ink}, mock: {padding: 12, borderRadius: radius.sm, backgroundColor: '#FFF6D8'}, mockText: {fontSize: 12, lineHeight: 18, color: '#655317'}, note: {fontSize: 11, color: colors.muted, textAlign: 'center'}});
