import { useState } from 'react'; import { Alert, StyleSheet, Text, View } from 'react-native'; import { CameraView, useCameraPermissions } from 'expo-camera'; import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Button } from '../components/Button'; import { colors, radius } from '../theme'; import type { RootStackParamList } from '../navigation/types'; import { QRService } from '../services/qr/QRService';

export function ScannerScreen({navigation}: NativeStackScreenProps<RootStackParamList, 'Scanner'>) {
  const [permission, requestPermission] = useCameraPermissions(); const [locked, setLocked] = useState(false);
  if (!permission) return <View style={styles.permission}/>;
  if (!permission.granted) return <View style={styles.permission}><Text style={styles.title}>Scan intentionally.</Text><Text style={styles.body}>Camera access is used only while this scanner is open. FaceCard does not upload or retain camera frames.</Text><Button label="Allow camera" onPress={requestPermission}/><Button label="Not now" variant="text" onPress={() => navigation.goBack()}/></View>;
  return <View style={styles.container}><CameraView style={StyleSheet.absoluteFill} facing="back" barcodeScannerSettings={{barcodeTypes: ['qr']}} onBarcodeScanned={locked ? undefined : ({data}) => { setLocked(true); try { navigation.replace('ScannedCard', {payload: QRService.decodeContactCard(data)}); } catch (error) { Alert.alert('Cannot open this QR', error instanceof Error ? error.message : 'Invalid QR code.', [{text: 'Scan again', onPress: () => setLocked(false)}]); } }}/><View style={styles.shade}><Text style={styles.cameraTitle}>Scan a FaceCard</Text><Text style={styles.cameraText}>Place the QR inside the frame</Text><View style={styles.frame}/><Button label="Cancel" variant="secondary" onPress={() => navigation.goBack()} style={styles.cancel}/></View></View>;
}
const styles = StyleSheet.create({container: {flex: 1, backgroundColor: '#000'}, permission: {flex: 1, padding: 24, gap: 18, justifyContent: 'center', backgroundColor: colors.paper}, title: {fontSize: 34, fontWeight: '700', color: colors.ink}, body: {fontSize: 16, lineHeight: 24, color: colors.muted}, shade: {flex: 1, alignItems: 'center', paddingTop: 90, paddingBottom: 44, backgroundColor: 'rgba(0,0,0,.32)'}, cameraTitle: {fontSize: 28, fontWeight: '700', color: colors.white}, cameraText: {color: colors.white, opacity: .82, marginTop: 8}, frame: {width: 278, height: 278, borderRadius: radius.lg, borderWidth: 3, borderColor: colors.white, marginTop: 70, flex: 1, maxHeight: 278}, cancel: {width: 180, marginTop: 'auto'}});
