import { Alert, Linking, StyleSheet, Text, View } from 'react-native'; import * as Clipboard from 'expo-clipboard'; import * as Contacts from 'expo-contacts/legacy'; import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Screen } from '../components/Screen'; import { Button } from '../components/Button'; import { colors, radius } from '../theme'; import type { RootStackParamList } from '../navigation/types'; import type { ContactFieldKey } from '../models'; import { messageFromError } from '../utils/errors';

const labels: Record<ContactFieldKey, string> = {email: 'Email', phone: 'Phone', website: 'Website', linkedin: 'LinkedIn', github: 'GitHub', company: 'Company', jobTitle: 'Job title', note: 'Note'};
export function ScannedCardScreen({route, navigation}: NativeStackScreenProps<RootStackParamList, 'ScannedCard'>) {
  const {payload} = route.params; const entries = Object.entries(payload.fields).filter(([, value]) => value) as [ContactFieldKey, string][];
  const save = async () => { try { const permission = await Contacts.requestPermissionsAsync(); if (!permission.granted) throw new Error('Contact permission was not granted.'); const name = payload.name ?? 'FaceCard contact'; const parts = name.split(/\s+/); await Contacts.addContactAsync({name, contactType: Contacts.ContactTypes.Person, firstName: parts[0] ?? name, lastName: parts.slice(1).join(' '), emails: payload.fields.email ? [{email: payload.fields.email, label: 'FaceCard'}] : undefined, phoneNumbers: payload.fields.phone ? [{number: payload.fields.phone, label: 'FaceCard'}] : undefined, urlAddresses: [payload.fields.website, payload.fields.linkedin, payload.fields.github].filter(Boolean).map((url) => ({url: url!, label: 'FaceCard'}),), company: payload.fields.company, jobTitle: payload.fields.jobTitle, note: payload.fields.note}); Alert.alert('Contact saved'); } catch (e) { Alert.alert('Could not save contact', messageFromError(e)); } };
  return <Screen><Text style={styles.eyebrow}>RECEIVED FACECARD</Text><Text style={styles.name}>{payload.name ?? 'Private FaceCard'}</Text>{payload.tagline && <Text style={styles.tagline}>{payload.tagline}</Text>}
    <View style={styles.shared}><Text style={styles.sharedTitle}>Shared with you</Text>{entries.length ? entries.map(([key, value]) => <View key={key} style={styles.row}><View><Text style={styles.label}>{labels[key]}</Text><Text numberOfLines={2} style={styles.value}>{value}</Text></View>{['website','linkedin','github'].includes(key) && <Button label="Open" variant="text" onPress={() => Linking.openURL(value)}/>}</View>) : <Text style={styles.empty}>No contact fields were included.</Text>}</View>
    <Button label="Save contact" onPress={save}/>{payload.fields.website && <Button label="Open website" variant="secondary" onPress={() => Linking.openURL(payload.fields.website!)}/>} {payload.fields.email && <Button label="Copy email" variant="secondary" onPress={async () => { await Clipboard.setStringAsync(payload.fields.email!); Alert.alert('Email copied'); }}/>}<Button label="Scan another" variant="text" onPress={() => navigation.replace('Scanner')}/>
    <Text style={styles.privacy}>This screen contains only properties physically present in the scanned QR.</Text>
  </Screen>;
}
const styles = StyleSheet.create({eyebrow: {fontSize: 11, color: colors.green, letterSpacing: 1.8, fontWeight: '800', marginTop: 16}, name: {fontSize: 38, lineHeight: 43, fontWeight: '700', color: colors.ink}, tagline: {fontSize: 18, color: colors.muted}, shared: {backgroundColor: colors.white, borderRadius: radius.lg, padding: 18, borderWidth: 1, borderColor: colors.line}, sharedTitle: {fontSize: 13, fontWeight: '800', color: colors.ink, marginBottom: 8}, row: {minHeight: 66, borderTopWidth: 1, borderTopColor: colors.soft, paddingVertical: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'}, label: {fontSize: 11, color: colors.muted, fontWeight: '700', textTransform: 'uppercase'}, value: {fontSize: 16, color: colors.ink, marginTop: 4, maxWidth: 270}, empty: {color: colors.muted, paddingVertical: 14}, privacy: {fontSize: 12, lineHeight: 18, textAlign: 'center', color: colors.muted}});
