import { Alert, Pressable, StyleSheet, Text, View } from 'react-native'; import * as Sharing from 'expo-sharing'; import { File, Paths } from 'expo-file-system'; import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Screen } from '../components/Screen'; import { Button } from '../components/Button'; import { PrivacyNote } from '../components/PrivacyNote'; import { colors, radius } from '../theme'; import type { RootStackParamList } from '../navigation/types'; import { useApp } from '../hooks/useApp'; import { messageFromError } from '../utils/errors';

export function SettingsScreen({navigation}: NativeStackScreenProps<RootStackParamList, 'Settings'>) {
  const app = useApp(); const reset = () => navigation.reset({index: 0, routes: [{name: 'Welcome'}]});
  const removeIdentity = () => Alert.alert('Delete identity?', 'This permanently removes the local identity metadata and all cards tied to it. Your original photos are not managed by FaceCard QR.', [{text: 'Cancel', style: 'cancel'}, {text: 'Delete identity', style: 'destructive', onPress: async () => { await app.deleteIdentity(); reset(); }}]);
  const removeAll = () => Alert.alert('Delete all local data?', 'Identity metadata, cards, preferences, and the onboarding state will be deleted from this device. Store purchase history remains with Apple or Google.', [{text: 'Cancel', style: 'cancel'}, {text: 'Delete everything', style: 'destructive', onPress: async () => { await app.deleteAllLocalData(); reset(); }}]);
  const exportConfig = async () => { if (!app.isPro) return navigation.navigate('Paywall'); try { const file = new File(Paths.cache, `facecard-config-${Date.now()}.json`); file.create({overwrite: true}); file.write(JSON.stringify({v: 1, exportedAt: new Date().toISOString(), cards: app.cards}, null, 2)); if (await Sharing.isAvailableAsync()) await Sharing.shareAsync(file.uri, {mimeType: 'application/json'}); } catch (e) { Alert.alert('Export failed', messageFromError(e)); } };
  const restore = async () => { try { const ok = await app.restorePurchases(); Alert.alert(ok ? 'Pro restored' : 'Nothing to restore', ok ? 'Your Pro features are active.' : 'No Pro entitlement was found.'); } catch (e) { Alert.alert('Restore failed', messageFromError(e)); } };
  return <Screen><Text style={styles.title}>Settings</Text><PrivacyNote>FaceCard QR has no cloud account and no biometric database. Identity metadata is held in device-protected storage.</PrivacyNote>
    <Text style={styles.section}>PURCHASES</Text><Row title={app.isPro ? 'FaceCard Pro' : 'Free tier'} detail={app.isPro ? 'Lifetime unlocked' : 'One card · basic fields'} onPress={() => !app.isPro && navigation.navigate('Paywall')}/><Row title="Restore purchases" onPress={restore}/><Row title="Export card configuration" detail="Pro · excludes biometric metadata" onPress={exportConfig}/>
    <Text style={styles.section}>PRIVACY & DATA</Text><View style={styles.info}><Text style={styles.infoTitle}>What is stored</Text><Text style={styles.infoBody}>A SHA-256 visual identity hash and its version in secure local storage; contact-card configuration in app-local storage. QR codes contain only your local ID and fields you enable.</Text></View>
    <Button label="Delete identity" variant="danger" onPress={removeIdentity}/><Button label="Delete all local data" variant="danger" onPress={removeAll}/>
    <Text style={styles.version}>FaceCard QR · MVP 1.0.0</Text>
  </Screen>;
}
function Row({title, detail, onPress}: {title: string; detail?: string; onPress: () => void}) { return <Pressable onPress={onPress} style={styles.row}><View><Text style={styles.rowTitle}>{title}</Text>{detail && <Text style={styles.detail}>{detail}</Text>}</View><Text style={styles.arrow}>›</Text></Pressable>; }
const styles = StyleSheet.create({title: {fontSize: 34, fontWeight: '700', color: colors.ink, marginTop: 12}, section: {fontSize: 11, letterSpacing: 1.7, color: colors.green, fontWeight: '800', marginTop: 10}, row: {backgroundColor: colors.white, borderRadius: radius.md, borderWidth: 1, borderColor: colors.line, minHeight: 66, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'}, rowTitle: {fontSize: 16, fontWeight: '600', color: colors.ink}, detail: {fontSize: 12, color: colors.muted, marginTop: 3}, arrow: {fontSize: 26, color: colors.muted}, info: {padding: 16, borderRadius: radius.md, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.line}, infoTitle: {fontSize: 15, fontWeight: '700', color: colors.ink}, infoBody: {fontSize: 13, lineHeight: 20, color: colors.muted, marginTop: 7}, version: {textAlign: 'center', color: colors.muted, fontSize: 11, marginVertical: 12}});
